### ISSUE TITLE
[PE-D][Tester B] Pie chart ui flaw 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W17-2/tp#126]
![Screenshot 2022-10-28 at 4.38.38 PM.png](https://raw.githubusercontent.com/mqchua/ped/master/files/a4820215-11b9-4ed5-be08-024070c18251.png)

There is only one income but there is a separation on the pie chart. 

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: mqchua/ped#3

**Comment by JasonYapzx** [comment]
This should not be declared as a bug, this is due to the implementation from JavaFX's graph library. Even with the line separation, it is apparent to the user that 100% of the graph is made up of the Income entry `Tuition Teaching` under the `Salary` category. Hence we will not be fixing this issue.
