### ISSUE TITLE
[PE-D][Tester D] Incorrect error message shown after an invalid edit command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W17-2/tp#141]
![image.png](https://raw.githubusercontent.com/nmtuan2001/ped/main/files/a18065fa-5923-418f-afad-4b13f0579a4e.png)

The tag is wrong here but the error message is regarding the entry type (which is correct).

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: nmtuan2001/ped#5

**Comment by JasonYapzx** [comment]
Hey, I am not sure if this is an immediate bug because the parser recognises this `i b/s` as the entry type that this user is trying to add in. Even though we do mention explicitly how to type the entry types, and other command prefixes.

I believe that we can specify further that PennyWise will treat erroneous prefixes as a continuation of the previous prefix's content just to warn users who are trying to break our application.

@AY2223S1-CS2103T-W17-2/developers 

![image](https://user-images.githubusercontent.com/63844743/199282854-a8963cfa-411a-4dbf-91eb-477e752755e3.png)

**Comment by EmilyOng** [comment]
Sorry for the late reply, I think that's a good idea!

**Comment by EmilyOng** [comment]
Closed by https://github.com/AY2223S1-CS2103T-W17-2/tp/pull/163, thanks @JasonYapzx do let me know if this closing wrong
